// Mocks generated by Mockito 5.4.5 from annotations
// in flutter_movie_app/test/ui/home/cubit/home_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_movie_app/data/models/movie.dart' as _i4;
import 'package:flutter_movie_app/data/models/person.dart' as _i8;
import 'package:flutter_movie_app/data/models/tv_show.dart' as _i6;
import 'package:flutter_movie_app/data/repositories/movie_repository.dart'
    as _i2;
import 'package:flutter_movie_app/data/repositories/person_repository.dart'
    as _i7;
import 'package:flutter_movie_app/data/repositories/tv_show_repository.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i2.MovieRepository {
  @override
  _i3.Future<List<_i4.Movie>> getNowPlayingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingMovies, []),
            returnValue: _i3.Future<List<_i4.Movie>>.value(<_i4.Movie>[]),
            returnValueForMissingStub: _i3.Future<List<_i4.Movie>>.value(
              <_i4.Movie>[],
            ),
          )
          as _i3.Future<List<_i4.Movie>>);

  @override
  _i3.Future<List<_i4.Movie>> getPopularMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovies, []),
            returnValue: _i3.Future<List<_i4.Movie>>.value(<_i4.Movie>[]),
            returnValueForMissingStub: _i3.Future<List<_i4.Movie>>.value(
              <_i4.Movie>[],
            ),
          )
          as _i3.Future<List<_i4.Movie>>);

  @override
  _i3.Future<List<_i4.Movie>> getTopRatedMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedMovies, []),
            returnValue: _i3.Future<List<_i4.Movie>>.value(<_i4.Movie>[]),
            returnValueForMissingStub: _i3.Future<List<_i4.Movie>>.value(
              <_i4.Movie>[],
            ),
          )
          as _i3.Future<List<_i4.Movie>>);

  @override
  _i3.Future<List<_i4.Movie>> getUpcomingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingMovies, []),
            returnValue: _i3.Future<List<_i4.Movie>>.value(<_i4.Movie>[]),
            returnValueForMissingStub: _i3.Future<List<_i4.Movie>>.value(
              <_i4.Movie>[],
            ),
          )
          as _i3.Future<List<_i4.Movie>>);
}

/// A class which mocks [TvShowRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvShowRepository extends _i1.Mock implements _i5.TvShowRepository {
  @override
  _i3.Future<List<_i6.TvShow>> getPopularTvShows() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTvShows, []),
            returnValue: _i3.Future<List<_i6.TvShow>>.value(<_i6.TvShow>[]),
            returnValueForMissingStub: _i3.Future<List<_i6.TvShow>>.value(
              <_i6.TvShow>[],
            ),
          )
          as _i3.Future<List<_i6.TvShow>>);
}

/// A class which mocks [PersonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonRepository extends _i1.Mock implements _i7.PersonRepository {
  @override
  _i3.Future<List<_i8.Person>> getPopularPeople() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularPeople, []),
            returnValue: _i3.Future<List<_i8.Person>>.value(<_i8.Person>[]),
            returnValueForMissingStub: _i3.Future<List<_i8.Person>>.value(
              <_i8.Person>[],
            ),
          )
          as _i3.Future<List<_i8.Person>>);
}
