// Mocks generated by Mockito 5.4.5 from annotations
// in flutter_movie_app/test/data/remote/impl/tv_show_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_movie_app/network/movie_api.dart' as _i3;
import 'package:flutter_movie_app/network/response/response.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMovieListResponse_0 extends _i1.SmartFake
    implements _i2.MovieListResponse {
  _FakeMovieListResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvShowListResponse_1 extends _i1.SmartFake
    implements _i2.TvShowListResponse {
  _FakeTvShowListResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePersonListResponse_2 extends _i1.SmartFake
    implements _i2.PersonListResponse {
  _FakePersonListResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieApi extends _i1.Mock implements _i3.MovieApi {
  @override
  _i4.Future<_i2.MovieListResponse> getNowPlayingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingMovies, []),
            returnValue: _i4.Future<_i2.MovieListResponse>.value(
              _FakeMovieListResponse_0(
                this,
                Invocation.method(#getNowPlayingMovies, []),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.MovieListResponse>.value(
              _FakeMovieListResponse_0(
                this,
                Invocation.method(#getNowPlayingMovies, []),
              ),
            ),
          )
          as _i4.Future<_i2.MovieListResponse>);

  @override
  _i4.Future<_i2.MovieListResponse> getPopularMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovies, []),
            returnValue: _i4.Future<_i2.MovieListResponse>.value(
              _FakeMovieListResponse_0(
                this,
                Invocation.method(#getPopularMovies, []),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.MovieListResponse>.value(
              _FakeMovieListResponse_0(
                this,
                Invocation.method(#getPopularMovies, []),
              ),
            ),
          )
          as _i4.Future<_i2.MovieListResponse>);

  @override
  _i4.Future<_i2.MovieListResponse> getTopRatedMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedMovies, []),
            returnValue: _i4.Future<_i2.MovieListResponse>.value(
              _FakeMovieListResponse_0(
                this,
                Invocation.method(#getTopRatedMovies, []),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.MovieListResponse>.value(
              _FakeMovieListResponse_0(
                this,
                Invocation.method(#getTopRatedMovies, []),
              ),
            ),
          )
          as _i4.Future<_i2.MovieListResponse>);

  @override
  _i4.Future<_i2.MovieListResponse> getUpcomingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingMovies, []),
            returnValue: _i4.Future<_i2.MovieListResponse>.value(
              _FakeMovieListResponse_0(
                this,
                Invocation.method(#getUpcomingMovies, []),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.MovieListResponse>.value(
              _FakeMovieListResponse_0(
                this,
                Invocation.method(#getUpcomingMovies, []),
              ),
            ),
          )
          as _i4.Future<_i2.MovieListResponse>);

  @override
  _i4.Future<_i2.TvShowListResponse> getPopularTvShows() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTvShows, []),
            returnValue: _i4.Future<_i2.TvShowListResponse>.value(
              _FakeTvShowListResponse_1(
                this,
                Invocation.method(#getPopularTvShows, []),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.TvShowListResponse>.value(
              _FakeTvShowListResponse_1(
                this,
                Invocation.method(#getPopularTvShows, []),
              ),
            ),
          )
          as _i4.Future<_i2.TvShowListResponse>);

  @override
  _i4.Future<_i2.PersonListResponse> getPopularPeople() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularPeople, []),
            returnValue: _i4.Future<_i2.PersonListResponse>.value(
              _FakePersonListResponse_2(
                this,
                Invocation.method(#getPopularPeople, []),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.PersonListResponse>.value(
              _FakePersonListResponse_2(
                this,
                Invocation.method(#getPopularPeople, []),
              ),
            ),
          )
          as _i4.Future<_i2.PersonListResponse>);
}
